// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ijcmrikahvhdskvwedvn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlqY21yaWthaHZoZHNrdndlZHZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5ODAzNzEsImV4cCI6MjA3MDU1NjM3MX0.v4mw9bu7ju_ossQgN2FdLI-SKa93cykATpW2vGxdgkY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});